server:
  port: 9775

spring:
  profiles:
    active: dev
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
    host: shopcloud.redis.host
  rabbitmq:
    host: shopcloud.rabbitmq.host
    port: 5672
    username: guest
    password: guest

shopcloud:
  mysql:
    admin:
      database: shopcloud_admin_dev

logging:
  level:
    console: INFO
    filter: INFO

id-generator:
  machine-code: 1  # id生成器机器掩码

# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。